---
swagger: "2.0"
info:
  description: "trying to reverse engineer the dribl.com public api"
  version: "1.0.5"
  title: "api.dribl.com"
  termsOfService: ""
  contact:
    email: ""
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "mc-api.dribl.com"
basePath: "/api"

