---
swagger: "2.0"
info:
  description: "trying to reverse engineer the dribl.com public api"
  title: "api.dribl.com"
  termsOfService: ""
  contact:
    email: ""
  license:
host: "mc-api.dribl.com"
basePath: "/api"

tags:
- name: "season"
  description: "Season to be played"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"

schemes:
- "https"

paths:
  /list/seasons:
    post:
      tags:
      - "season"
      summary: "list all seasons"
      description: "list all seasons"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
